### title
# baseURL = 'https://rocketeer1998.github.io/CJY_website/'
# baseURL = 'https://rocketeer1998.org/'
baseURL = "https://rocketeer1998.github.io/CJY_website/"
languageCode = 'en-us'
title = 'Jiayu Chen'
theme = 'ananke'
relativeURLs = true
canonifyURLs = true

### no effect
#[params]
#  subtitle = 'RA in Uppsala University'
#  [params.contact]
#    email = 'jiayu.chen@igp.uu.se'
#    phone = '+46 0720101251'
  
### menu  
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4

### 
[mediaTypes]
  [mediaTypes.'image/jpeg']
    delimiter = '.'
    suffixes = ['jpg', 'jpeg', 'jpe', 'jif', 'jfif']
    

    
    
    
    
