### title
baseURL = 'https://github.com/rocketeer1998/CJY_website'
languageCode = 'en-us'
title = 'Jiayu Chen'
theme = 'ananke'

### no effect
#[params]
#  subtitle = 'RA in Uppsala University'
#  [params.contact]
#    email = 'jiayu.chen@igp.uu.se'
#    phone = '+46 0720101251'
  
### menu  
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4


    
    
    
    
