### title
# baseURL = 'https://rocketeer1998.github.io/CJY_website/'
# baseURL = 'https://rocketeer1998.org/'
baseURL = "https://rocketeer1998.github.io/CJY_website/"
languageCode = 'en-us'
title = 'Jiayu Chen'
theme = 'ananke'
relativeURLs = false
canonifyURLs = true

### social networks
[params.ananke.social.follow]
new_window_icon = true
networks = ["github", "bluesky", "instagram"]

[params.ananke.social.github]
username = "rocketeer1998"
profilelink = "https://github.com/rocketeer1998"

[params.ananke.social.bluesky]
username = "rocketeer1998.bsky.social"

[params.ananke.social.instagram]
username = "jiayu83439"

### menu  
[[menu.main]]
  
  name = "Blog"
  url = "/blog/"
  weight = 4


    
    
    
