### title
baseURL = 'https://rocketeer1998.org/'
languageCode = 'en-us'
title = 'Jiayu Chen'
theme = 'ananke'

### no effect
#[params]
#  subtitle = 'RA in Uppsala University'
#  [params.contact]
#    email = 'jiayu.chen@igp.uu.se'
#    phone = '+46 0720101251'
  
### menu  
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 4

###
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'


    
    
    
    
